### ISSUE TITLE
Documentation site is broken (404)

### ISSUE THREAD

**Issue by tacheometry** [NobleDraconian/Dragon-Engine#58]

**Comment by NobleDraconian** [comment]
Thanks for the notice! Should be fixed in a few minutes. It's worth noting that the documentation site is incomplete and the existing documentation is pretty outdated, so the documentation pages may not be completely reliable at this time.

**Comment by NobleDraconian** [comment]
I've re-deployed the site and it can be found at https://nobledraconian.github.io/Dragon-Engine/. I've also updated the repository's link to the website as well.l
